### ISSUE TITLE
the maddash.yaml example in rerports section has references to regulartesting, BWCTL and generate_gui_configuration

### ISSUE THREAD

**Issue by igarny** [perfsonar/maddash#57]
```
  id: throughput_mesh_report
    rule:
      rules: 

...............
...............


solutions:
              - 'If you just configured this grid in the mesh, you may just need to wait as it takes several hours for throughput data to populate (depending on the interval between tests)'
              - Verify maddash is configured properly. Look in the files under /var/log/maddash/ for any errors. Things to look for are incorrect paths to checks or connection errors.
              - Verify that /usr/lib/perfsonar/bin/generate_gui_configuration has run recently and you are looking at an accurate test mesh
              - Verify that your measurement archive(s) are running
              - Verify no firewall is blocking maddash from reaching your measurement archive(s)
              - Verify your hosts are downloading the mesh configuration file and that there are tests defined in /etc/perfsonar/regulartesting.conf
              - Verify that regular testing is running (/etc/init.d/perfsonar-regulartesting status)
              - Verify your hosts are able to reach their configured measurement archive and that there are no errors in /var/log/perfsonar/regulartesting.log 
```

perhaps also:
```
'If recently added to the mesh, verify the mesh config file has been downloaded by the end-hosts since the update. It may also take several hours for the first BWCTL test to run on this host.'
                    - 'If recently removed from the mesh, verify that /usr/lib/perfsonar/bin/generate_gui_configuration has run recently and you are looking at an accurate test mesh'
                    - Verify NTP is synced on this host
                    - 'Verify the local and remote sites allow access to TCP port 4823, TCP/UDP ports 6001-6200, and TCP/UDP ports 5001-5900' 
```
